# Generated by Django 3.0.1 on 2020-01-15 17:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='car',
            options={'ordering': ['updated']},
        ),
    ]
