# Generated by Django 3.0.1 on 2020-09-15 17:54

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='car',
            options={'ordering': ['updated']},
        ),
        migrations.RemoveField(
            model_name='car',
            name='uuid',
        ),
        migrations.AddField(
            model_name='car',
            name='manufacturing_date',
            field=models.DateField(default=datetime.datetime(2020, 9, 15, 17, 54, 34, 394136, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddIndex(
            model_name='car',
            index=models.Index(fields=['brand'], name='cars_car_brand_i_8369a6_idx'),
        ),
    ]
