# Generated by Django 3.0.1 on 2020-01-22 10:30

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0002_auto_20200115_1726'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='manufacturing_date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
